seed: 42
device: cuda:0
num_steps_per_env: 128
max_iterations: 1000
empirical_normalization: false
policy:
  class_name: ActorCritic
  init_noise_std: 1.0
  actor_hidden_dims:
  - 128
  - 64
  critic_hidden_dims:
  - 128
  - 64
  activation: elu
algorithm:
  class_name: PPO
  value_loss_coef: 1.0
  use_clipped_value_loss: true
  clip_param: 0.1
  entropy_coef: 2.0e-05
  num_learning_epochs: 10
  num_mini_batches: 64
  learning_rate: 0.0001
  schedule: adaptive
  gamma: 0.95
  lam: 0.91
  desired_kl: 0.003
  max_grad_norm: 0.5
clip_actions: null
save_interval: 100
experiment_name: dragon_grasp_analysis
run_name: entr_2e-5
logger: tensorboard
neptune_project: isaaclab
wandb_project: isaaclab
resume: false
load_run: .*
load_checkpoint: model_.*.pt
